name = "k0iro-v2"
compatibility_date = "2025-02-06"

[build]
command = "chmod +x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"

[vars]
HUGO_VERSION = "0.148.2"
HUGO_ENV = "production"
NODE_VERSION = "24.13.0"
TZ = "America/Chicago"